# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()

ar = np.array([1,2,3])
ar
# Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[4,5,6],
                [7,8,9]])
ar2
# Create a 3-dimensional Numpy array using np.array()
ar3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
ar3


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [17]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
ar.ndim,ar.shape,type(ar),ar.size,ar.dtype

(1, (3,), numpy.ndarray, 3, dtype('int64'))

In [18]:
# Attributes of 2-dimensional array
ar2.ndim,ar2.shape,type(ar2),ar.size,ar2.dtype

(2, (2, 3), numpy.ndarray, 3, dtype('int64'))

In [19]:
# Attributes of 3-dimensional array
ar3.ndim,ar3.shape,type(ar3),ar3.size,ar3.dtype

(3, (1, 3, 3), numpy.ndarray, 9, dtype('int64'))

In [24]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
new_array = pd.DataFrame(ar2)
new_array

0  1  2
0  4  5  6
1  7  8  9

In [25]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(1,101)
range_array[:20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
# Create a random array with numbers betw(een 0 and 10 of size (7, 2)
random_array = np.random.randint(10,size=(7,2))
random_array

array([[6, 7],
       [1, 5],
       [5, 5],
       [2, 7],
       [8, 9],
       [8, 6],
       [1, 0]])

In [35]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.random((3,5))
random_float_array

array([[0.70073982, 0.69167587, 0.36802635, 0.65944099, 0.85582481],
       [0.15357961, 0.01044704, 0.13906842, 0.41040882, 0.86399715],
       [0.48645086, 0.64747641, 0.49081174, 0.76856821, 0.15962618]])

In [37]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_2 = np.random.randint(0,10,size=(4,6))
random_array_2


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numbers = np.random.randint(1,10, size=(3,7))
random_numbers

# Find the unique numbers in the array you just created
np.unique(random_numbers)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [42]:
# Find the 0'th index of the latest array you created
random_array_2[0]

array([6, 3, 7, 4, 6, 9])

In [43]:
random_array_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [44]:
# Get the first 2 rows of latest array you created
random_array_2[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [47]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_2[:2,:2]

array([[6, 3],
       [2, 6]])

In [51]:
# Create a random array of numbers between 0 & 10 and an array of ones
random_numbers_2 =  np.random.randint(10,size=(3,5))
ones_2 = np.ones((3,5))
# both of size (3, 5), save them both to variables
random_numbers_2,
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
random_numbers_2

array([[3, 0, 0, 9, 3],
       [6, 1, 2, 0, 4],
       [0, 7, 0, 0, 1]])

In [52]:
# Add the two arrays together
random_numbers_2 + ones_2

array([[ 4.,  1.,  1., 10.,  4.],
       [ 7.,  2.,  3.,  1.,  5.],
       [ 1.,  8.,  1.,  1.,  2.]])

In [54]:
# Create another array of ones of shape (5, 3)
ones_3 = np.ones((5,3))
ones_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
# Try add the array of ones and the other most recent array together
ones_3 + random_numbers_2.T

array([[ 4.,  7.,  1.],
       [ 1.,  2.,  8.],
       [ 1.,  3.,  1.],
       [10.,  1.,  1.],
       [ 4.,  5.,  2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [57]:
# Create another array of ones of shape (3, 5)
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
# Subtract the new array of ones from the other most recent array
random_numbers_2 - ones_2

array([[ 2., -1., -1.,  8.,  2.],
       [ 5.,  0.,  1., -1.,  3.],
       [-1.,  6., -1., -1.,  0.]])

In [59]:
# Multiply the ones array with the latest array
random_numbers_2 * ones_2

array([[3., 0., 0., 9., 3.],
       [6., 1., 2., 0., 4.],
       [0., 7., 0., 0., 1.]])

In [62]:
# Take the latest array to the power of 2 using '**'
power_array = random_numbers_2 **2
power_array

array([[ 9,  0,  0, 81,  9],
       [36,  1,  4,  0, 16],
       [ 0, 49,  0,  0,  1]])

In [64]:
# Do the same thing with np.square()
np.square(random_numbers)

array([[81, 49, 81, 64,  4,  1, 49],
       [49, 64, 25,  9, 64, 36,  9],
       [ 1,  9, 25,  9,  1, 25, 49]])

In [65]:
# Find the mean of the latest array using np.mean()
np.mean(power_array)

13.733333333333333

In [66]:
# Find the maximum of the latest array using np.max()
np.max(power_array)

81

In [67]:
# Find the minimum of the latest array using np.min()
np.min(power_array)

0

In [68]:
# Find the standard deviation of the latest array
np.std(power_array)

22.89822894655586

In [69]:
# Find the variance of the latest array
np.var(power_array)

524.3288888888887

In [71]:
# Reshape the latest array to (3, 5, 1)
power_array.shape
power_array.reshape(3,5,1)

array([[[ 9],
        [ 0],
        [ 0],
        [81],
        [ 9]],

       [[36],
        [ 1],
        [ 4],
        [ 0],
        [16]],

       [[ 0],
        [49],
        [ 0],
        [ 0],
        [ 1]]])

In [72]:
# Transpose the latest array
power_array.T

array([[ 9, 36,  0],
       [ 0,  1, 49],
       [ 0,  4,  0],
       [81,  0,  0],
       [ 9, 16,  1]])

What does the transpose do?

In [73]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(seed=0)
new_array_1 = np.random.randint(10,size=(3,3))
new_array_2 = np.random.randint(10,size=(3,2))

In [74]:
new_array_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [75]:
new_array_2

array([[4, 7],
       [6, 8],
       [8, 1]])

In [76]:
# Perform a dot product on the two newest arrays you created
np.dot(new_array_1,new_array_2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [77]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
new_array3 = np.random.randint(10,size=(4,3))
new_array4 = np.random.randint(10,size=(4,3))

In [78]:
new_array3

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [79]:
new_array4

array([[3, 5, 0],
       [2, 3, 8],
       [1, 3, 3],
       [3, 7, 0]])

In [81]:
# Perform a dot product on the two newest arrays you created
np.dot(new_array3,new_array4.T)

array([[ 53,  89,  48,  67],
       [ 29,  59,  26,  31],
       [ 67, 114,  60,  83],
       [ 27,  17,  13,  33]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [83]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar5 = np.random.randint(5,size=(2,3))
ar6 = np.random.randint(5,size=(2,3))

In [84]:
ar5

array([[1, 1, 1],
       [0, 2, 4]])

In [85]:
ar6

array([[3, 3, 2],
       [4, 2, 0]])

In [86]:
# Compare the two arrays with '>'
ar5 > ar6

array([[False, False, False],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [87]:
# Compare the two arrays with '>='
ar5 >= ar6

array([[False, False, False],
       [False,  True,  True]])

In [88]:
# Find which elements of the first array are greater than 7
ar5 > 7

array([[False, False, False],
       [False, False, False]])

In [89]:
# Which parts of each array are equal? (try using '==')
ar5 == ar6

array([[False, False, False],
       [False,  True, False]])

In [90]:
# Sort one of the arrays you just created in ascending order
np.sort(ar5)

array([[1, 1, 1],
       [0, 2, 4]])

In [91]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar5)

array([[0, 1, 2],
       [0, 1, 2]])

In [92]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar5)

5

In [93]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar5)

3

In [95]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar5,axis=1)

array([0, 2])

In [96]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar5,axis=0)

array([1, 0, 0])

In [97]:
# Create an array of normally distributed random numbers
normal_array = np.random.normal(loc=0, scale=1, size=10)

normal_array

array([ 0.04575852, -0.18718385,  1.53277921,  1.46935877,  0.15494743,
        0.37816252, -0.88778575, -1.98079647, -0.34791215,  0.15634897])

In [101]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
# evenly_spaced_array = np.linspace(1, 100, 10,dtype=int) for integer numbers
evenly_spaced_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.