In [1]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(2)
# number of laptops sold
laptop_sales = np.random.randint(30, size=(5,4))
laptop_sales

array([[ 8, 15, 13,  8],
       [22, 11, 18, 11],
       [ 8,  7,  2, 17],
       [11, 21, 15, 26],
       [20, 28, 20,  5]])

In [4]:
#weekly sales
weekly_sales = pd.DataFrame(laptop_sales, index=["Monday", "Tuesday","Wednesday","Thursday","Friday"],columns=["HP","MacBook","Toshiba","Lenovo"])
weekly_sales

HP  MacBook  Toshiba  Lenovo
Monday      8       15       13       8
Tuesday    22       11       18      11
Wednesday   8        7        2      17
Thursday   11       21       15      26
Friday     20       28       20       5

In [5]:
#Prices
laptop_prices = np.array([1300,2500,1400,1800])
laptop_prices

array([1300, 2500, 1400, 1800])

In [7]:
prices = pd.DataFrame(laptop_prices.reshape(1,4),index=["Prices"],columns=["HP","MacBook","Toshiba","Lenovo"])
prices

HP  MacBook  Toshiba  Lenovo
Prices  1300     2500     1400    1800

In [13]:
total_sales = laptop_prices.dot(laptop_sales.T)
total_sales

array([ 80500, 101100,  61300, 134600, 133000])

In [15]:
prices

HP  MacBook  Toshiba  Lenovo
Prices  1300     2500     1400    1800

In [16]:
weekly_sales

HP  MacBook  Toshiba  Lenovo
Monday      8       15       13       8
Tuesday    22       11       18      11
Wednesday   8        7        2      17
Thursday   11       21       15      26
Friday     20       28       20       5

In [18]:
daily_sales = prices.dot(weekly_sales.T)
daily_sales

Monday  Tuesday  Wednesday  Thursday  Friday
Prices   80500   101100      61300    134600  133000

In [19]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

HP  MacBook  Toshiba  Lenovo  Total ($)
Monday      8       15       13       8      80500
Tuesday    22       11       18      11     101100
Wednesday   8        7        2      17      61300
Thursday   11       21       15      26     134600
Friday     20       28       20       5     133000